[package]
name = "tauri-plugin-window-state"
publish = false
version = "0.1.0"
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
tauri = "1"
thiserror = "1.0.56"
log = "0.4.20"
bincode = "1.3"
bitflags = "2.4.2"
